apiVersion: v1
kind: Secret
metadata:
  name: mhf-secrets
  namespace: mental-health-forum
type: Opaque
stringData:
  jwt-secret: "mhf-super-secret-jwt-key-2024-for-development-only-change-in-prod"
  user-db-password: "postgres123"
  forum-db-password: "postgres123"
  postgres-user: "postgres"
